version: 2

updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: gomod
    directory: "/broker-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: gomod
    directory: "/auth-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 99