// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type KeyPair struct {
	Uuid       string    `json:"uuid"`
	PrivetKey  []byte    `json:"privet_key"`
	PublicKey  []byte    `json:"public_key"`
	ExpiredAt  time.Time `json:"expired_at"`
	CreatedAt  time.Time `json:"created_at"`
	ModifiedAt time.Time `json:"modified_at"`
}

type User struct {
	Uuid           string         `json:"uuid"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	Phone          string         `json:"phone"`
	HashedPassword string         `json:"hashed_password"`
	Address        string         `json:"address"`
	UserType       string         `json:"user_type"`
	AddedBy        sql.NullString `json:"added_by"`
	CreatedAt      time.Time      `json:"created_at"`
	ModifiedAt     time.Time      `json:"modified_at"`
}
