// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetKeys(ctx context.Context) (KeyPair, error)
	GetUser(ctx context.Context, uuid string) (User, error)
	GetUsername(ctx context.Context, uuid string) (string, error)
	UpdateKeys(ctx context.Context, arg UpdateKeysParams) (KeyPair, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
