name: Auth Service

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
        - "assets/**"
        - "broker-service/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build
      working-directory: ./auth-service
      run: go build -v ./...

    - name: Test
      working-directory: ./auth-service
      run: go test -v ./...
